version: '3'
services:
  db:
    container_name: internshop-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  phpmyadmin:
    container_name: internshop-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    links:
      - db
    expose:
      - 80
    ports:
      - 9999:80
  redis:
    container_name: internshop-redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379

