#spring:
#  profiles: test
#
#  datasource:
#    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
#    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    database: H2
#    openInView: false
#    show_sql: false
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop